<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <RootNamespace>BGManager</RootNamespace>
    <OutputType>WinExe</OutputType>
    <ApplicationIcon>logo.ico</ApplicationIcon>
    <StartupObject>BGManager.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BGShared\BGShared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="logo.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
